Models/OrderDetails.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ShoppingFantasy.Models
{
    public class OrderDetails
    {
        public int Id { get; set; }

        [Required]
        public int OrderId { get; set; }

        [ForeignKey("OrderId")]
        [ValidateNever]
        public OrderHeader OrderHeader { get; set; }

        [Required]
        public int ProductId { get; set; }

        [ForeignKey("ProductId")]
        [ValidateNever]
        [DisplayName("Article")]
        public Product Product { get; set; }

        [DisplayName("Nombre")]
        public int Count { get; set; }

        [DisplayName("Prix")]
		[Column(TypeName = "decimal(18,2)")]
		[DataType(DataType.Currency)]
		public decimal Price { get; set; }

    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace ShoppingFantasy.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ShoppingFantasy.Data;
using ShoppingFantasy.Models;

namespace ShoppingFantasy.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly ApplicationDbContext _db;

        public IndexModel(ILogger<IndexModel> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public IList<Category> Categories { get; set; } = default!;

        public async Task OnGetAsync()
        {
             Categories =  await _db.Categories
                .Include(c => c.Products)
                .ToListAsync();

        }
    }
}

Pages/MonPanier/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ShoppingFantasy.Data;
using ShoppingFantasy.Models;
using ShoppingFantasy.Utility;
using ShoppingFantasy.ViewModels;
using Stripe.Checkout;
using System.Security.Claims;

namespace ShoppingFantasy.Pages.MonPanier
{

    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public ShoppingCartVM ShoppingCart { get; set; } = default!;

        public decimal ShippingPrice { get; } = SD.ShippingCost;

        public async Task<IActionResult> OnGet()
        {
            if (User.Identity.IsAuthenticated)
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

                ShoppingCartVM cartVM = new()
                {
                    ListCart = await _db.ShoppingCarts
                        .Include(sc => sc.Product)
                        .ThenInclude(p => p.Picture)
                        .Where(sc => sc.ApplicationUserId == claim.Value)
                        .ToListAsync(),

                    OrderHeader = new()
                };

                foreach (var cart in cartVM.ListCart)
                {
                    cart.Price = GetTotalPrice(cart);
                    cartVM.OrderHeader.OrderTotal += (cart.Price * cart.Count);
                }

                if (cartVM.OrderHeader.OrderTotal > (double)SD.ShippingFreeCost)
                {
                    cartVM.OrderHeader.FreeShipping = true;
                }
                else
                {
                    cartVM.OrderHeader.FreeShipping = false;
                    cartVM.OrderHeader.OrderTotal += (double)SD.ShippingCost;
                }

                ShoppingCart = cartVM;

                return Page();
            }
            else
            {
				return RedirectToPage("Identity/Account/Login");
            }
            
        }

        public async Task<IActionResult> OnPostAsync()
        {
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

			var shoppingCart = new ShoppingCartVM()
			{
				ListCart = await _db.ShoppingCarts.Include(s => s.Product).Where(s => s.ApplicationUserId == claim.Value).ToListAsync(),
				OrderHeader = new()

			};

			shoppingCart.OrderHeader.AppUser = await _db.AppUsers.FirstOrDefaultAsync(o => o.Id == claim.Value);

			shoppingCart.OrderHeader.Name = shoppingCart.OrderHeader.AppUser.Name;
			shoppingCart.OrderHeader.SurName = shoppingCart.OrderHeader.AppUser.Surname;
			shoppingCart.OrderHeader.StreetAddress = shoppingCart.OrderHeader.AppUser.Address;
			shoppingCart.OrderHeader.City = shoppingCart.OrderHeader.AppUser.City;
			shoppingCart.OrderHeader.PostalCode = shoppingCart.OrderHeader.AppUser.PostalCode;
			shoppingCart.OrderHeader.AddressComplement = shoppingCart.OrderHeader.AppUser.AddressComplement;

			foreach (var cart in shoppingCart.ListCart)
			{
				cart.Price = GetTotalPrice(cart);
				shoppingCart.OrderHeader.OrderTotal += (cart.Price * cart.Count);
			}

			//await _db.AddAsync(shoppingCart.OrderHeader);
			//await _db.SaveChangesAsync();
			ShoppingCart = shoppingCart;

			return Redirect("MonPanier/Test"/*, new {ShoppingCart = shoppingCart}*/);
		}

		
	

		public async Task<IActionResult> OnGetRemove(int cartId)
		{
			// Retrieve the item in the cart
			var item = _db.ShoppingCarts.FirstOrDefault(c => c.Id == cartId);

			// Remove the item from the cart and update the database
			_db.Remove(item);
			await _db.SaveChangesAsync();
			return RedirectToPage("Index");
		}


		private double GetTotalPrice(ShoppingCart sp)
        {
            decimal productPrice;

            if (sp.Product.IsInPromo)
                productPrice = sp.Product.PromoPrice;
            else
                productPrice = sp.Product.Price;
            return (double)productPrice;
        }



    }
}

Pages/OrderIndex.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ShoppingFantasy.Data;
using ShoppingFantasy.Models;
using ShoppingFantasy.Utility;
using ShoppingFantasy.ViewModels;
using System.Security.Claims;

namespace ShoppingFantasy.Pages
{
    public class OrderIndexModel : PageModel
    {

        public readonly ApplicationDbContext _db;

        public OrderIndexModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public OrderVM OrderVM { get; set; } = default!;
        public IEnumerable<OrderHeader> OrderHeaders { get; set; } = default!;

        public async Task OnGet()
        {
            IEnumerable<OrderHeader> orderHeaders;

            if(User.IsInRole(SD.Role_Admin))
            {
                orderHeaders = await _db.OrderHeaders.Include(oh => oh.AppUser)
                    .ToListAsync();
            }
            else
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                orderHeaders = await _db.OrderHeaders.Include(oh => oh.AppUser)
                    .Where(oh => oh.AppUserId == claim.Value)
                    .ToListAsync();
            }

            OrderHeaders = orderHeaders;
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ShoppingFantasy.Data;
using ShoppingFantasy.Models;

namespace ShoppingFantasy.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;
        private readonly ApplicationDbContext _db;

        public PrivacyModel(ILogger<PrivacyModel> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        [BindProperty]
        public ContactUs Contact { get; set; } = default!;

        public async Task OnGet()
        {
            var contactUs = await _db.ContactUs.FirstOrDefaultAsync();
            Contact = contactUs;
        }

        public async Task<IActionResult> OnPost()
        {
            var ctus = await _db.ContactUs.Where(c => c.Id == 1).FirstOrDefaultAsync();
            ctus.Message = Contact.Message;

            _db.ContactUs.Update(ctus);
           await  _db.SaveChangesAsync();

            return RedirectToPage("Privacy");
        }
    }
}

Pages/ProductByCategory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Routing.Template;
using Microsoft.EntityFrameworkCore;
using ShoppingFantasy.Data;
using ShoppingFantasy.Models;
using System.Security.Claims;

namespace ShoppingFantasy.Pages
{
    public class ProductByCategoryModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public ProductByCategoryModel(ApplicationDbContext db)
        {
            _db = db;
        }


        public Category Category { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _db.Categories == null) return NotFound();

            var category = await _db.Categories.Include(c => c.Products)
                                               .ThenInclude(p => p.Picture)
                                               .FirstOrDefaultAsync(c => c.Id == id);

            if (category == null) return NotFound();
            else Category = category;

            return Page();
        }
        //public async Task<IActionResult> OnPostAsync(int id)
        //{
        //    var product = await _db.Products.FirstOrDefaultAsync(p => p.Id == id);
        //    var claimsIdentity = (ClaimsIdentity)User.Identity;
        //    var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);


        //    if ( product == null)
        //    {
        //        TempData["error"] = "un probleme est survenue, actualisez la page et re-essayez s'il vous plait.";
        //        return Page();
        //    }
        //    else
        //    {
        //    }
        //}
    }
}

Pages/ProductDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using ShoppingFantasy.Data;
using ShoppingFantasy.Models;
using System.Security.Claims;

namespace ShoppingFantasy.Pages
{
    public class ProductDetailsModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public ProductDetailsModel(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public ShoppingCart ShoppingCart { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int id)
        {
            ShoppingCart cartObj = new()
            {
                Count = 1,
                ProductId = id,
                Product = await _db.Products
                            .Include(p => p.Category)
                            .Include(p => p.Picture)
                            .FirstOrDefaultAsync(p => p.Id == id)
            };

            ShoppingCart = cartObj;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            ShoppingCart.ApplicationUserId = claim.Value;

            ShoppingCart cartFromDb = await _db.ShoppingCarts
                .FirstOrDefaultAsync(s => s.ApplicationUserId == claim.Value && s.ProductId == ShoppingCart.ProductId);

            if (cartFromDb == null)
            {
                var shoppingCart = new ShoppingCart
                {
                    ProductId = ShoppingCart.ProductId,
                    Count = ShoppingCart.Count,
                    ApplicationUserId = ShoppingCart.ApplicationUserId
                };

                await _db.ShoppingCarts.AddAsync(shoppingCart);

            }
            else
            {
                cartFromDb.Count += ShoppingCart.Count;
                //_db.ShoppingCarts.Update(cartFromDb);
                
            }


            await _db.SaveChangesAsync();
            TempData["success"] = $"{ShoppingCart.Count} article(s) ajoute(s) a votre panier .";
            return RedirectToPage("/Index");

        }
    }
}

Pages/Promotion.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ShoppingFantasy.Data;
using ShoppingFantasy.Models;

namespace ShoppingFantasy.Pages
{
    public class PromotionModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public PromotionModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public List<Product> Products { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync()
        {
            var productList = await _db.Products.Include(p => p.Picture)
                .Where(p => p.IsInPromo)
                .ToListAsync();

            if (productList == null || productList.Count == 0)
            {
                TempData["Cle"] = "Aucune promotion actuellement";
                return RedirectToPage("/index");
            }

            Products = productList;
            return Page();
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Accueil";
}

@*<div class="row text-center">

    <h1 class="pt-2 pb-4 title">Nos Categories d'articles</h1>
</div>*@

<div class="row d-sm-flex text-center pt-2 pb-4">
    @foreach (var item in Model.Categories)
    {
        <div class="col col-lg-3 col-md-4 col-6">
            <div class="card text-white bg-primary mb-3 hoverable" style="max-width: auto;">
                <div class="card-header">
                    <h4 class="card-title">@item.Name</h4>
                </div>
                <a asp-page="productbycategory" asp-route-id="@item.Id">
                    <div class="card-body">
                        <img class="card-img-top" src="@item.ImageUrl" alt="@item.Name">
                    </div>
                </a>
            </div>
        </div>
    }
</div>

<style>
    .modal-content {
        background-color: whitesmoke;
        border-color: #333;
        box-shadow: 0 3px 9px rgba(0,0,0,0.5);
        color: #333;
    }

    img {
        max-width: 200px;
        max-height: 200px;
        border-radius: 6px;
        transition: transform .2s;
        margin-bottom: 10px;
    }

        img:hover {
            transform: scale(1.1) rotate(5deg);
            border: 2px solid black;
            box-shadow: 10px 5px 5px black;
        }

    .hoverable {
        position: relative;
    }

        .hoverable:hover {
            z-index: 10;
            border: 2px solid black;
            box-shadow: 10px 5px 5px black;
            transform: scale(1.1) rotate(-1.2deg);
        }

        .title {
            z-index:10;
        }

</style>

Pages/OrderConfirmation.cshtml
@page
@model ShoppingFantasy.Pages.OrderConfirmationModel
@{
}

<div class="container row pt-4">
    <div class="col-12 text-center">
        <h1 class="text-primary text-center">Merci pour votre Achat !</h1>
            Le numéro de votre commande : @Model.Id <br /><br />
            <img src="~/images/boy_swim_money.png" alt="merci pour votre achat!" />
    </div>
</div>

Pages/OrderIndex.cshtml
@page
@model ShoppingFantasy.Pages.OrderIndexModel
@using Newtonsoft.Json
@{
    ViewData["Title"] = "Mes Ordres";

}



<div class= "pt-5 container ">
    <div class="text-center pb-2">
        <h3 class="text-info">Mes Ordres</h3>
    </div>

    <input hidden id="order-info" value="@JsonConvert.SerializeObject(Model.OrderHeaders)" />

    <table id="table" class="table table-hover table-striped rounded" style="width:100%">
        <thead class=" text-bg-dark rounded">
             <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Nom</th>
                <th>Livraison</th>
                <th>Telephone</th>
                <th>E-mail</th>
                <th>Statut</th>
                <th>Total</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>



@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
    <script src="
https://cdn.jsdelivr.net/npm/moment@2.29.4/moment.min.js
"></script>
    <script src="
https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/locale/fr.min.js
"></script>
<script type="text/javascript" defer>

$(document).ready(  function () {
              
            const data = JSON.parse(document.getElementById("order-info").value);
            data.map(d => d.OrderDate = moment(d.OrderDate).format('L'));
            data.map(d => d.OrderTotal = (d.OrderTotal).toLocaleString('fr-FR', {
                style: 'currency',
                currency: 'EUR'
            }))

    $('#table').DataTable({
                language: {
                    url: "//cdn.datatables.net/plug-ins/1.13.1/i18n/fr-FR.json"
                },
                data: data,
         "columns" : [
                {data: "Id"},
                {data: "OrderDate"},
                {data: "Name"},
                {data: "Carrier"},
                {data: "PhoneNumber"},
                {data: "AppUser.Email"},
                {data: "OrderStatus"},
                {data: "OrderTotal"},
                {"data": "Id",
                "render": function (data) {
                    return `
                        <div class="w-75 btn-group" role="group">
                        <a href="/OrderDetails?orderId=${data}"
                                class="btn btn-info mx-2"> <i class="bi bi-eye-fill"></i></a>
                      
					</div>
                        `
                },
                "width": "5%"
            }
         ]

         
    });
} );

</script>

}

Pages/Panier.cshtml
@page
@using Microsoft.AspNetCore.Authorization;

@model ShoppingFantasy.Pages.PanierModel
@{
	ViewData["Title"] = "Mon Panier";
}

@if (User.Identity.IsAuthenticated)
{
	<form method="post" >
		<input asp-for="ShoppingCart" hidden />
		<br />
		<div class="container pt-4 pb-4">
			<div class="card">
				<div class="card-header bg-primary ml-0">
					<div class="row">
						<div class="col-6  pt-2">
							<i class="fa fa-shopping-cart"></i> &nbsp;
							<strong class="text-light">Mon Panier</strong>
						</div>
						<div class="col-6 text-end">
							<a asp-page="/index" class="btn btn-outline-light btn-sm">Continuer mes achats</a>
						</div>
					</div>
				</div>

				<div class="card-body bg-secondary">

					@if (Model.ShoppingCart.ListCart.Count() != 0)
					{
						@foreach (var item in Model.ShoppingCart.ListCart)
						{
							<div class="row">
								<div class="d-none d-lg-block col-lg-1 text-center py-2">
									<img src="@item.Product.Picture.FirstOrDefault().PictureUrl" class="rounded" width="100%" />
								</div>
								<div class="col-12 col-lg-6 pt-md-3">
									<h5><strong>@item.Product.Name</strong></h5>
								</div>
								<div class="col-12  col-lg-5 text-center row">
									<div class="col-4 text-md-right pt-4">
										<h6>
											<strong>
												@item.Price <i class="bi bi-currency-euro"></i>
												<span class="text-muted">&nbsp;x&nbsp;</span>@item.Count
											</strong>
										</h6>
									</div>

									<div class="col-2 col-sm-4 col-lg-2 text-right pt-2">
										<a asp-page-handler="Minus" asp-route-cartId="@item.Id" class="btn btn-danger "><i class="bi bi-dash-circle"></i></a>
									</div>
									<div class="col-2 col-sm-4 col-lg-2 text-right pt-2 pr-2 pl-2">
										<a asp-page-handler="Remove" asp-route-cartId="@item.Id" class="btn btn-dark"><i class="bi bi-trash-fill"></i></a>
									</div>
									<div class="col-2 col-sm-4 col-lg-2 text-right pt-2">
										<a asp-page-handler="Plus" asp-route-cartId="@item.Id" class="btn btn-success "><i class="bi bi-plus-circle"></i></a>
									</div>
								</div>
							</div>
							<hr />
						}
						<div class="row">
							<div class="col-12 col-md-6 offset-md-6 col-lg-4 offset-lg-8 pr-4">
								<ul class="list-group unlisted">
									<li class="list-group-item d-flex justify-content-between bg-light">
										<span class="text-info"> Valeur du Panier </span>
										<strong class="text-info">@Model.ShoppingCart.OrderHeader.OrderTotal <i class="bi bi-currency-euro"></i></strong>
									</li>
								</ul>
							</div>
						</div>
						<div class="card-footer">
							<div class="card-footer row">
								<div class="col-sm-12 col-lg-4 col-md-6 offset-lg-8 offset-md-6 ">
									<button type="submit" class="btn btn-success ">Valider</button>
								</div>
							</div>
						</div>
					}
					else
					{
						<div class="text-center text-info pt-4 pb-4">
							<h3>Votre panier est vide</h3>
						</div>
					}
				</div>
			</div>
	</form>

	


}
else
{
	<div class="text center pt-3">
		             <a asp-area="Identity" asp-page="/Account/Register" class="btn btn-dark pb-2">Créer un compte</a>
                    <a asp-area="Identity" asp-page="/Account/Login" class="btn btn-dark">Se Connecter</a>
	</div>
}

Pages/ProductByCategory.cshtml
@page
@model ShoppingFantasy.Pages.ProductByCategoryModel
@{
    ViewData["Title"] = $"{Model.Category.Name}";
}

<ul class="list-unstyled">

    @foreach (var product in Model.Category.Products)
    {

        <li class="container bg-secondary oi-media-pause my-3 rounded hoverable" style="display: flex;">
            <button type="button" class="btn " data-bs-toggle="modal" data-bs-target="#productModal-@product.Id">
            <div class="media-img-wrapper mr-2 pt-2 px-2">
                <img class="media-img rounded" src="@product.Picture.FirstOrDefault().PictureUrl" alt="@product.Name" />
            </div>
            </button>

            <div class="media-body text-center" style="display: flex;">
                    <h4 class="mb-0 pt-3">@product.Name</h4>
                
                <div class="flex-row px-4 pb-3 pt-3">
                    @if (product.IsInPromo)
                    {
                        <h5 class="price"><strike class="text-danger">@product.Price <i class="bi bi-currency-euro"></i></strike></h5>
                        <h5 class="price"><strong class="text-success">@product.PromoPrice <i class="bi bi-currency-euro"></i></strong></h5>
                    }
                    else
                    {
                        <h5 class="price"><strong class="text-success">@product.Price <i class="bi bi-currency-euro"></i></strong></h5>
                    }
                    <a  asp-route-id="@product.Id" asp-page="/ProductDetails">
                    <button class="btn btn-info btn-sm"><i class="bi bi-eye-fill"></i> Details</button>
                    </a>
                </div>
            </div>
            
        </li>

        <!-- Modal -->
        <div class="modal fade modal-lg" id="productModal-@product.Id" tabindex="-1" aria-labelledby="productModalLabel-@product.Id" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content text-center">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5 text-center" id="productModalLabel-@product.Id">@product.Name</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
                    </div>
                    <div class="modal-body">
                        <div id="productCarousel-@product.Id" class="carousel slide" data-bs-ride="carousel">
                            <!-- Indicateurs -->
                            <ol class="carousel-indicators">
                                @foreach (var picture in product.Picture)
                                {
                                    <li data-bs-target="#productCarousel-@product.Id" data-bs-slide-to="@product.Picture.ToList().FindIndex(p => p == picture)" class="@(product.Picture.ToList().FindIndex(p => p == picture) == 0 ? "active" : "")"></li>
                                }
                            </ol>
                            <!-- Diapositives -->
                            <div class="carousel-inner">
                                @foreach (var picture in product.Picture)
                                {
                                    <div class="carousel-item @(product.Picture.ToList().FindIndex(p => p == picture) == 0 ? "active" : "")">
                                        <img src="@picture.PictureUrl" alt="@product.Name" class="img-fluid rounded shadow-lg" />
                                    </div>
                                }
                            </div>
                            <!-- Contrôles -->
                            <a class="carousel-control-prev text-info" href="#productCarousel-@product.Id" role="button" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Précédent</span>
                            </a>
                            <a class="carousel-control-next text-info" href="#productCarousel-@product.Id" role="button" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Suivant</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <script>
            $(document).ready(function () {
                $('#productModal-@product.Id').on('shown.bs.modal', function () {
                    $('#productCarousel-@product.Id').carousel();
                }).on('hidden.bs.modal', function () {
                    $('#productCarousel-@product.Id').carousel('pause');
                });
            });
        </script>

    }
</ul>

<style>
    .modal-content {
        background-color: whitesmoke;
        border-color: #333;
        box-shadow: 0 3px 9px rgba(0,0,0,0.5);
        color: #333;
    }

    img {
        max-width: 200px;
        max-height: 200px;
        border-radius: 6px;
        transition: transform .2s;
        margin-bottom: 10px;
    }

        img:hover {
            transform: scale(1.1) rotate(5deg);
            border: 2px solid black;
            box-shadow: 10px 5px 5px black;
        }

    .hoverable {
        position: relative;
    }

        .hoverable:hover {
            z-index: 10;
            border: 2px solid black;
            box-shadow: 10px 5px 5px black;
    @*transform: scale(1.1) rotate(-1.2deg);*@
        }
</style>